-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 1.6
--C:\lscc\diamond\3.14\ispfpga\bin\nt64\scuba.exe -w -n SIN -lang vhdl -synth lse -bus_exp 7 -bb -arch mg5a00 -type cosine -addr_width 10 -width 8 -pfu -input_reg -input_reg -mode 4 -output_reg -area -pipeline 1 

-- Wed Feb 18 12:26:24 2026

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library xp2;
use xp2.components.all;
-- synopsys translate_on

entity SIN is
    port (
        Clock: in  std_logic; 
        ClkEn: in  std_logic; 
        Reset: in  std_logic; 
        Theta: in  std_logic_vector(9 downto 0); 
        Sine: out  std_logic_vector(7 downto 0));
end SIN;

architecture Structure of SIN is

    -- internal signal declarations
    signal func_or_inet_1: std_logic;
    signal func_or_inet: std_logic;
    signal lx_ne0: std_logic;
    signal lx_ne0_inv: std_logic;
    signal mx_ctrl_r_inv: std_logic;
    signal rom_addr0_r: std_logic;
    signal rom_addr0_r_1: std_logic;
    signal rom_addr0_r_2: std_logic;
    signal rom_addr0_r_3: std_logic;
    signal rom_addr0_r_4: std_logic;
    signal rom_addr0_r_5: std_logic;
    signal rom_addr0_r_6: std_logic;
    signal mx_ctrl_r: std_logic;
    signal rom_addr0_r_7: std_logic;
    signal mx_ctrl_r_1: std_logic;
    signal rom_dout: std_logic;
    signal rom_dout_1: std_logic;
    signal rom_dout_2: std_logic;
    signal rom_dout_3: std_logic;
    signal rom_dout_4: std_logic;
    signal rom_dout_5: std_logic;
    signal rom_dout_6: std_logic;
    signal sinromoutsel: std_logic;
    signal rom_dout_7: std_logic;
    signal out_sel_i: std_logic;
    signal rom_dout_8: std_logic;
    signal rom_dout_9: std_logic;
    signal rom_dout_10: std_logic;
    signal rom_dout_11: std_logic;
    signal rom_dout_12: std_logic;
    signal rom_dout_13: std_logic;
    signal rom_dout_14: std_logic;
    signal out_sel: std_logic;
    signal rom_dout_15: std_logic;
    signal sinout_pre: std_logic;
    signal sinout_pre_1: std_logic;
    signal sinout_pre_2: std_logic;
    signal sinout_pre_3: std_logic;
    signal sinout_pre_4: std_logic;
    signal sinout_pre_5: std_logic;
    signal sinout_pre_6: std_logic;
    signal sinout_pre_7: std_logic;
    signal rom_addr0_r_n: std_logic;
    signal rom_addr0_r_inv: std_logic;
    signal rom_addr0_r_n_1: std_logic;
    signal rom_addr0_r_n_2: std_logic;
    signal co0: std_logic;
    signal rom_addr0_r_1_inv: std_logic;
    signal rom_addr0_r_2_inv: std_logic;
    signal rom_addr0_r_n_3: std_logic;
    signal rom_addr0_r_n_4: std_logic;
    signal co1: std_logic;
    signal rom_addr0_r_3_inv: std_logic;
    signal rom_addr0_r_4_inv: std_logic;
    signal rom_addr0_r_n_5: std_logic;
    signal rom_addr0_r_n_6: std_logic;
    signal co2: std_logic;
    signal rom_addr0_r_5_inv: std_logic;
    signal rom_addr0_r_6_inv: std_logic;
    signal rom_addr0_r_n_7: std_logic;
    signal co3: std_logic;
    signal rom_addr0_r_7_inv: std_logic;
    signal rom_dout_7_ffin: std_logic;
    signal rom_dout_6_ffin: std_logic;
    signal rom_dout_5_ffin: std_logic;
    signal rom_dout_4_ffin: std_logic;
    signal rom_dout_3_ffin: std_logic;
    signal rom_dout_2_ffin: std_logic;
    signal rom_dout_1_ffin: std_logic;
    signal rom_dout_ffin: std_logic;
    signal rom_addr0_r_n_8: std_logic;
    signal rom_addr0_r_n_9: std_logic;
    signal rom_addr0_r_n_10: std_logic;
    signal rom_addr0_r_n_11: std_logic;
    signal rom_addr0_r_n_12: std_logic;
    signal rom_addr0_r_n_13: std_logic;
    signal rom_addr0_r_n_14: std_logic;
    signal rom_addr0_r_n_15: std_logic;
    signal rom_dout_n: std_logic;
    signal scuba_vhi: std_logic;
    signal rom_dout_inv: std_logic;
    signal rom_dout_n_1: std_logic;
    signal rom_dout_n_2: std_logic;
    signal co0_1: std_logic;
    signal rom_dout_1_inv: std_logic;
    signal rom_dout_2_inv: std_logic;
    signal rom_dout_n_3: std_logic;
    signal rom_dout_n_4: std_logic;
    signal co1_1: std_logic;
    signal rom_dout_3_inv: std_logic;
    signal rom_dout_4_inv: std_logic;
    signal rom_dout_n_5: std_logic;
    signal rom_dout_n_6: std_logic;
    signal co2_1: std_logic;
    signal rom_dout_5_inv: std_logic;
    signal rom_dout_6_inv: std_logic;
    signal rom_dout_n_7: std_logic;
    signal co3_1: std_logic;
    signal rom_dout_7_inv: std_logic;
    signal scuba_vlo: std_logic;

    -- local component declarations
    component AND2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component FADD2B
        port (A0: in  std_logic; A1: in  std_logic; B0: in  std_logic; 
            B1: in  std_logic; CI: in  std_logic; COUT: out  std_logic; 
            S0: out  std_logic; S1: out  std_logic);
    end component;
    component FD1P3DX
    -- synopsys translate_off
        generic (GSR : in String);
    -- synopsys translate_on
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component INV
        port (A: in  std_logic; Z: out  std_logic);
    end component;
    component MUX21
        port (D0: in  std_logic; D1: in  std_logic; SD: in  std_logic; 
            Z: out  std_logic);
    end component;
    component ROM16X1
    -- synopsys translate_off
        generic (initval : in String);
    -- synopsys translate_on
        port (AD3: in  std_logic; AD2: in  std_logic; AD1: in  std_logic; 
            AD0: in  std_logic; DO0: out  std_logic);
    end component;
    component ROM256X1
    -- synopsys translate_off
        generic (INITVAL : in String);
    -- synopsys translate_on
        port (AD7: in  std_logic; AD6: in  std_logic; AD5: in  std_logic; 
            AD4: in  std_logic; AD3: in  std_logic; AD2: in  std_logic; 
            AD1: in  std_logic; AD0: in  std_logic; DO0: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    attribute GSR : string; 
    attribute initval : string; 
    attribute initval of LUT4_2 : label is "0xfffe";
    attribute initval of LUT4_1 : label is "0xfffe";
    attribute initval of LUT4_0 : label is "0xfffe";
    attribute GSR of FF_27 : label is "ENABLED";
    attribute GSR of FF_26 : label is "ENABLED";
    attribute GSR of FF_25 : label is "ENABLED";
    attribute GSR of FF_24 : label is "ENABLED";
    attribute GSR of FF_23 : label is "ENABLED";
    attribute GSR of FF_22 : label is "ENABLED";
    attribute GSR of FF_21 : label is "ENABLED";
    attribute GSR of FF_20 : label is "ENABLED";
    attribute GSR of FF_19 : label is "ENABLED";
    attribute GSR of FF_18 : label is "ENABLED";
    attribute GSR of FF_17 : label is "ENABLED";
    attribute GSR of FF_16 : label is "ENABLED";
    attribute GSR of FF_15 : label is "ENABLED";
    attribute GSR of FF_14 : label is "ENABLED";
    attribute GSR of FF_13 : label is "ENABLED";
    attribute GSR of FF_12 : label is "ENABLED";
    attribute GSR of FF_11 : label is "ENABLED";
    attribute GSR of FF_10 : label is "ENABLED";
    attribute GSR of FF_9 : label is "ENABLED";
    attribute GSR of FF_8 : label is "ENABLED";
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute initval of triglut_1_0_7 : label is "0x0000000000000000000000000000000000000000000000000000000000000000";
    attribute initval of triglut_1_0_6 : label is "0x000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF";
    attribute initval of triglut_1_0_5 : label is "0x0000000000FFFFFFFFFFF00000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFF";
    attribute initval of triglut_1_0_4 : label is "0x00001FFFFF000007FFFFF0000007FFFFFF800000000FFFFFFFFFFFFFFFFFFFFF";
    attribute initval of triglut_1_0_3 : label is "0x007FE003FF001FF8007FF000FFF8003FFF80007FFFF000000FFFFFFFFFFFFFFF";
    attribute initval of triglut_1_0_2 : label is "0x0F83E0FC1F07E0F81F83F03F03F81FC07F807F803FF001FFF0000FFFFFFFFFFF";
    attribute initval of triglut_1_0_1 : label is "0x718C631CE718E718E39C71C71C78E1C387878787C1F07E07F01FF001FFFFFFFF";
    attribute initval of triglut_1_0_0 : label is "0x96B5A52D696969692DA49249249B26CD99999998CE738E38F1E0F07E01FFFFFF";
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    INV_17: INV
        port map (A=>rom_addr0_r_7, Z=>rom_addr0_r_7_inv);

    INV_16: INV
        port map (A=>rom_addr0_r_6, Z=>rom_addr0_r_6_inv);

    INV_15: INV
        port map (A=>rom_addr0_r_5, Z=>rom_addr0_r_5_inv);

    INV_14: INV
        port map (A=>rom_addr0_r_4, Z=>rom_addr0_r_4_inv);

    INV_13: INV
        port map (A=>rom_addr0_r_3, Z=>rom_addr0_r_3_inv);

    INV_12: INV
        port map (A=>rom_addr0_r_2, Z=>rom_addr0_r_2_inv);

    INV_11: INV
        port map (A=>rom_addr0_r_1, Z=>rom_addr0_r_1_inv);

    INV_10: INV
        port map (A=>rom_addr0_r, Z=>rom_addr0_r_inv);

    INV_9: INV
        port map (A=>rom_dout_7, Z=>rom_dout_7_inv);

    INV_8: INV
        port map (A=>rom_dout_6, Z=>rom_dout_6_inv);

    INV_7: INV
        port map (A=>rom_dout_5, Z=>rom_dout_5_inv);

    INV_6: INV
        port map (A=>rom_dout_4, Z=>rom_dout_4_inv);

    INV_5: INV
        port map (A=>rom_dout_3, Z=>rom_dout_3_inv);

    INV_4: INV
        port map (A=>rom_dout_2, Z=>rom_dout_2_inv);

    INV_3: INV
        port map (A=>rom_dout_1, Z=>rom_dout_1_inv);

    INV_2: INV
        port map (A=>rom_dout, Z=>rom_dout_inv);

    LUT4_2: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0xfffe")
        -- synopsys translate_on
        port map (AD3=>rom_addr0_r_n_8, AD2=>rom_addr0_r_n_9, 
            AD1=>rom_addr0_r_n_10, AD0=>rom_addr0_r_n_11, 
            DO0=>func_or_inet);

    LUT4_1: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0xfffe")
        -- synopsys translate_on
        port map (AD3=>rom_addr0_r_n_12, AD2=>rom_addr0_r_n_13, 
            AD1=>rom_addr0_r_n_14, AD0=>rom_addr0_r_n_15, 
            DO0=>func_or_inet_1);

    LUT4_0: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0xfffe")
        -- synopsys translate_on
        port map (AD3=>func_or_inet, AD2=>func_or_inet_1, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>lx_ne0);

    INV_1: INV
        port map (A=>lx_ne0, Z=>lx_ne0_inv);

    INV_0: INV
        port map (A=>mx_ctrl_r, Z=>mx_ctrl_r_inv);

    AND2_t0: AND2
        port map (A=>mx_ctrl_r_inv, B=>lx_ne0_inv, Z=>out_sel_i);

    FF_27: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>Theta(0), SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_addr0_r);

    FF_26: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>Theta(1), SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_addr0_r_1);

    FF_25: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>Theta(2), SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_addr0_r_2);

    FF_24: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>Theta(3), SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_addr0_r_3);

    FF_23: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>Theta(4), SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_addr0_r_4);

    FF_22: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>Theta(5), SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_addr0_r_5);

    FF_21: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>Theta(6), SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_addr0_r_6);

    FF_20: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>Theta(7), SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_addr0_r_7);

    FF_19: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>Theta(8), SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>mx_ctrl_r);

    FF_18: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>Theta(9), SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>mx_ctrl_r_1);

    muxb_23: MUX21
        port map (D0=>rom_addr0_r_n, D1=>rom_addr0_r, SD=>mx_ctrl_r, 
            Z=>rom_addr0_r_n_8);

    muxb_22: MUX21
        port map (D0=>rom_addr0_r_n_1, D1=>rom_addr0_r_1, SD=>mx_ctrl_r, 
            Z=>rom_addr0_r_n_9);

    muxb_21: MUX21
        port map (D0=>rom_addr0_r_n_2, D1=>rom_addr0_r_2, SD=>mx_ctrl_r, 
            Z=>rom_addr0_r_n_10);

    muxb_20: MUX21
        port map (D0=>rom_addr0_r_n_3, D1=>rom_addr0_r_3, SD=>mx_ctrl_r, 
            Z=>rom_addr0_r_n_11);

    muxb_19: MUX21
        port map (D0=>rom_addr0_r_n_4, D1=>rom_addr0_r_4, SD=>mx_ctrl_r, 
            Z=>rom_addr0_r_n_12);

    muxb_18: MUX21
        port map (D0=>rom_addr0_r_n_5, D1=>rom_addr0_r_5, SD=>mx_ctrl_r, 
            Z=>rom_addr0_r_n_13);

    muxb_17: MUX21
        port map (D0=>rom_addr0_r_n_6, D1=>rom_addr0_r_6, SD=>mx_ctrl_r, 
            Z=>rom_addr0_r_n_14);

    muxb_16: MUX21
        port map (D0=>rom_addr0_r_n_7, D1=>rom_addr0_r_7, SD=>mx_ctrl_r, 
            Z=>rom_addr0_r_n_15);

    FF_17: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rom_dout_7_ffin, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_dout_7);

    FF_16: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rom_dout_6_ffin, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_dout_6);

    FF_15: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rom_dout_5_ffin, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_dout_5);

    FF_14: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rom_dout_4_ffin, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_dout_4);

    FF_13: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rom_dout_3_ffin, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_dout_3);

    FF_12: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rom_dout_2_ffin, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_dout_2);

    FF_11: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rom_dout_1_ffin, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_dout_1);

    FF_10: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rom_dout_ffin, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>rom_dout);

    FF_9: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>mx_ctrl_r_1, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>sinromoutsel);

    muxb_15: MUX21
        port map (D0=>rom_dout, D1=>rom_dout_n, SD=>sinromoutsel, 
            Z=>rom_dout_8);

    muxb_14: MUX21
        port map (D0=>rom_dout_1, D1=>rom_dout_n_1, SD=>sinromoutsel, 
            Z=>rom_dout_9);

    muxb_13: MUX21
        port map (D0=>rom_dout_2, D1=>rom_dout_n_2, SD=>sinromoutsel, 
            Z=>rom_dout_10);

    muxb_12: MUX21
        port map (D0=>rom_dout_3, D1=>rom_dout_n_3, SD=>sinromoutsel, 
            Z=>rom_dout_11);

    muxb_11: MUX21
        port map (D0=>rom_dout_4, D1=>rom_dout_n_4, SD=>sinromoutsel, 
            Z=>rom_dout_12);

    muxb_10: MUX21
        port map (D0=>rom_dout_5, D1=>rom_dout_n_5, SD=>sinromoutsel, 
            Z=>rom_dout_13);

    muxb_9: MUX21
        port map (D0=>rom_dout_6, D1=>rom_dout_n_6, SD=>sinromoutsel, 
            Z=>rom_dout_14);

    muxb_8: MUX21
        port map (D0=>rom_dout_7, D1=>rom_dout_n_7, SD=>sinromoutsel, 
            Z=>rom_dout_15);

    FF_8: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>out_sel_i, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>out_sel);

    muxb_7: MUX21
        port map (D0=>rom_dout_8, D1=>scuba_vlo, SD=>out_sel, 
            Z=>sinout_pre);

    muxb_6: MUX21
        port map (D0=>rom_dout_9, D1=>scuba_vlo, SD=>out_sel, 
            Z=>sinout_pre_1);

    muxb_5: MUX21
        port map (D0=>rom_dout_10, D1=>scuba_vlo, SD=>out_sel, 
            Z=>sinout_pre_2);

    muxb_4: MUX21
        port map (D0=>rom_dout_11, D1=>scuba_vlo, SD=>out_sel, 
            Z=>sinout_pre_3);

    muxb_3: MUX21
        port map (D0=>rom_dout_12, D1=>scuba_vlo, SD=>out_sel, 
            Z=>sinout_pre_4);

    muxb_2: MUX21
        port map (D0=>rom_dout_13, D1=>scuba_vlo, SD=>out_sel, 
            Z=>sinout_pre_5);

    muxb_1: MUX21
        port map (D0=>rom_dout_14, D1=>scuba_vlo, SD=>out_sel, 
            Z=>sinout_pre_6);

    muxb_0: MUX21
        port map (D0=>rom_dout_15, D1=>scuba_vlo, SD=>out_sel, 
            Z=>sinout_pre_7);

    FF_7: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>sinout_pre, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>Sine(0));

    FF_6: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>sinout_pre_1, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>Sine(1));

    FF_5: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>sinout_pre_2, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>Sine(2));

    FF_4: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>sinout_pre_3, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>Sine(3));

    FF_3: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>sinout_pre_4, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>Sine(4));

    FF_2: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>sinout_pre_5, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>Sine(5));

    FF_1: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>sinout_pre_6, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>Sine(6));

    FF_0: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>sinout_pre_7, SP=>ClkEn, CK=>Clock, CD=>Reset, 
            Q=>Sine(7));

    neg_rom_addr0_r_n_0: FADD2B
        port map (A0=>scuba_vlo, A1=>rom_addr0_r_inv, B0=>scuba_vlo, 
            B1=>scuba_vhi, CI=>scuba_vlo, COUT=>co0, S0=>open, 
            S1=>rom_addr0_r_n);

    neg_rom_addr0_r_n_1: FADD2B
        port map (A0=>rom_addr0_r_1_inv, A1=>rom_addr0_r_2_inv, 
            B0=>scuba_vlo, B1=>scuba_vlo, CI=>co0, COUT=>co1, 
            S0=>rom_addr0_r_n_1, S1=>rom_addr0_r_n_2);

    neg_rom_addr0_r_n_2: FADD2B
        port map (A0=>rom_addr0_r_3_inv, A1=>rom_addr0_r_4_inv, 
            B0=>scuba_vlo, B1=>scuba_vlo, CI=>co1, COUT=>co2, 
            S0=>rom_addr0_r_n_3, S1=>rom_addr0_r_n_4);

    neg_rom_addr0_r_n_3: FADD2B
        port map (A0=>rom_addr0_r_5_inv, A1=>rom_addr0_r_6_inv, 
            B0=>scuba_vlo, B1=>scuba_vlo, CI=>co2, COUT=>co3, 
            S0=>rom_addr0_r_n_5, S1=>rom_addr0_r_n_6);

    neg_rom_addr0_r_n_4: FADD2B
        port map (A0=>rom_addr0_r_7_inv, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>co3, COUT=>open, S0=>rom_addr0_r_n_7, 
            S1=>open);

    triglut_1_0_7: ROM256X1
        -- synopsys translate_off
        generic map (initval=> "0x0000000000000000000000000000000000000000000000000000000000000000")
        -- synopsys translate_on
        port map (AD7=>rom_addr0_r_n_15, AD6=>rom_addr0_r_n_14, 
            AD5=>rom_addr0_r_n_13, AD4=>rom_addr0_r_n_12, 
            AD3=>rom_addr0_r_n_11, AD2=>rom_addr0_r_n_10, 
            AD1=>rom_addr0_r_n_9, AD0=>rom_addr0_r_n_8, 
            DO0=>rom_dout_7_ffin);

    triglut_1_0_6: ROM256X1
        -- synopsys translate_off
        generic map (initval=> "0x000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF")
        -- synopsys translate_on
        port map (AD7=>rom_addr0_r_n_15, AD6=>rom_addr0_r_n_14, 
            AD5=>rom_addr0_r_n_13, AD4=>rom_addr0_r_n_12, 
            AD3=>rom_addr0_r_n_11, AD2=>rom_addr0_r_n_10, 
            AD1=>rom_addr0_r_n_9, AD0=>rom_addr0_r_n_8, 
            DO0=>rom_dout_6_ffin);

    triglut_1_0_5: ROM256X1
        -- synopsys translate_off
        generic map (initval=> "0x0000000000FFFFFFFFFFF00000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFF")
        -- synopsys translate_on
        port map (AD7=>rom_addr0_r_n_15, AD6=>rom_addr0_r_n_14, 
            AD5=>rom_addr0_r_n_13, AD4=>rom_addr0_r_n_12, 
            AD3=>rom_addr0_r_n_11, AD2=>rom_addr0_r_n_10, 
            AD1=>rom_addr0_r_n_9, AD0=>rom_addr0_r_n_8, 
            DO0=>rom_dout_5_ffin);

    triglut_1_0_4: ROM256X1
        -- synopsys translate_off
        generic map (initval=> "0x00001FFFFF000007FFFFF0000007FFFFFF800000000FFFFFFFFFFFFFFFFFFFFF")
        -- synopsys translate_on
        port map (AD7=>rom_addr0_r_n_15, AD6=>rom_addr0_r_n_14, 
            AD5=>rom_addr0_r_n_13, AD4=>rom_addr0_r_n_12, 
            AD3=>rom_addr0_r_n_11, AD2=>rom_addr0_r_n_10, 
            AD1=>rom_addr0_r_n_9, AD0=>rom_addr0_r_n_8, 
            DO0=>rom_dout_4_ffin);

    triglut_1_0_3: ROM256X1
        -- synopsys translate_off
        generic map (initval=> "0x007FE003FF001FF8007FF000FFF8003FFF80007FFFF000000FFFFFFFFFFFFFFF")
        -- synopsys translate_on
        port map (AD7=>rom_addr0_r_n_15, AD6=>rom_addr0_r_n_14, 
            AD5=>rom_addr0_r_n_13, AD4=>rom_addr0_r_n_12, 
            AD3=>rom_addr0_r_n_11, AD2=>rom_addr0_r_n_10, 
            AD1=>rom_addr0_r_n_9, AD0=>rom_addr0_r_n_8, 
            DO0=>rom_dout_3_ffin);

    triglut_1_0_2: ROM256X1
        -- synopsys translate_off
        generic map (initval=> "0x0F83E0FC1F07E0F81F83F03F03F81FC07F807F803FF001FFF0000FFFFFFFFFFF")
        -- synopsys translate_on
        port map (AD7=>rom_addr0_r_n_15, AD6=>rom_addr0_r_n_14, 
            AD5=>rom_addr0_r_n_13, AD4=>rom_addr0_r_n_12, 
            AD3=>rom_addr0_r_n_11, AD2=>rom_addr0_r_n_10, 
            AD1=>rom_addr0_r_n_9, AD0=>rom_addr0_r_n_8, 
            DO0=>rom_dout_2_ffin);

    triglut_1_0_1: ROM256X1
        -- synopsys translate_off
        generic map (initval=> "0x718C631CE718E718E39C71C71C78E1C387878787C1F07E07F01FF001FFFFFFFF")
        -- synopsys translate_on
        port map (AD7=>rom_addr0_r_n_15, AD6=>rom_addr0_r_n_14, 
            AD5=>rom_addr0_r_n_13, AD4=>rom_addr0_r_n_12, 
            AD3=>rom_addr0_r_n_11, AD2=>rom_addr0_r_n_10, 
            AD1=>rom_addr0_r_n_9, AD0=>rom_addr0_r_n_8, 
            DO0=>rom_dout_1_ffin);

    triglut_1_0_0: ROM256X1
        -- synopsys translate_off
        generic map (initval=> "0x96B5A52D696969692DA49249249B26CD99999998CE738E38F1E0F07E01FFFFFF")
        -- synopsys translate_on
        port map (AD7=>rom_addr0_r_n_15, AD6=>rom_addr0_r_n_14, 
            AD5=>rom_addr0_r_n_13, AD4=>rom_addr0_r_n_12, 
            AD3=>rom_addr0_r_n_11, AD2=>rom_addr0_r_n_10, 
            AD1=>rom_addr0_r_n_9, AD0=>rom_addr0_r_n_8, 
            DO0=>rom_dout_ffin);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    neg_rom_dout_n_0: FADD2B
        port map (A0=>scuba_vlo, A1=>rom_dout_inv, B0=>scuba_vlo, 
            B1=>scuba_vhi, CI=>scuba_vlo, COUT=>co0_1, S0=>open, 
            S1=>rom_dout_n);

    neg_rom_dout_n_1: FADD2B
        port map (A0=>rom_dout_1_inv, A1=>rom_dout_2_inv, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>co0_1, COUT=>co1_1, S0=>rom_dout_n_1, 
            S1=>rom_dout_n_2);

    neg_rom_dout_n_2: FADD2B
        port map (A0=>rom_dout_3_inv, A1=>rom_dout_4_inv, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>co1_1, COUT=>co2_1, S0=>rom_dout_n_3, 
            S1=>rom_dout_n_4);

    neg_rom_dout_n_3: FADD2B
        port map (A0=>rom_dout_5_inv, A1=>rom_dout_6_inv, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>co2_1, COUT=>co3_1, S0=>rom_dout_n_5, 
            S1=>rom_dout_n_6);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    neg_rom_dout_n_4: FADD2B
        port map (A0=>rom_dout_7_inv, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, CI=>co3_1, COUT=>open, S0=>rom_dout_n_7, 
            S1=>open);

end Structure;

-- synopsys translate_off
library xp2;
configuration Structure_CON of SIN is
    for Structure
        for all:AND2 use entity xp2.AND2(V); end for;
        for all:FADD2B use entity xp2.FADD2B(V); end for;
        for all:FD1P3DX use entity xp2.FD1P3DX(V); end for;
        for all:INV use entity xp2.INV(V); end for;
        for all:MUX21 use entity xp2.MUX21(V); end for;
        for all:ROM16X1 use entity xp2.ROM16X1(V); end for;
        for all:ROM256X1 use entity xp2.ROM256X1(V); end for;
        for all:VHI use entity xp2.VHI(V); end for;
        for all:VLO use entity xp2.VLO(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
